### ISSUE TITLE
create LoggerEndpoint class for logging errors

### ISSUE THREAD

**Issue by Mattihew** [UCY-Team/yeovil_microsoft_cognitive_ai#48]
shoud act similar to Logger class i.e. have a static `LoggerEndpoint.log(String sessionId, Level lvl, String msg)`

needs to log errors to a particular session.

**Comment by Mattihew** [comment]
# Ideas

- posibly reasign the javascript `console.log` function to our own function

**Comment by jake-lewis** [comment]
# Implementation  Notes
log method requires a concrete instance of LoggingEndpoint, maybe should be static or have a mechanism for statically logging to s specific session?

Currently getting log messages by registering as an observer, meaning the update() method is being used. This could be a problem i.e. requires casting of "image" object from WebcamServlet to ensure its a message and not actuially an image. This also means that anything listening to WebcamServlet would recieve messages thinking that they might be an object

**Comment by Mattihew** [comment]
I would suggest that LoggingEndpoint should have a static map of 
`Map<String, Set<LoggingEndpoint>>`(where the String is the httpSessionId). onOpen a LoggingEndpoint should add it's self, onClose remove it's self. When an error is logged a sessionId is provided and a message is sent to all LoggingEndpoints in the set mapped to that id. No observer needed.

**Comment by Mattihew** [comment]
or rather it adds it's self onMessage recieved, not onOpen.

**Comment by jake-lewis** [comment]
Yeah I completely forgot about your comments in the task description
